esphome:
  comment: "Sonoff iFan04-L"

esp8266:
  board: esp01_1m

status_led:
  pin:
    number: 13
    inverted: true

logger:
  baud_rate: 0

uart:
  tx_pin: 1
  rx_pin: 3
  baud_rate: 9600

fan:
  - platform: speed
    id: ifan04
    name: ""
    output: ifan04_output
    speed_count: 3
    restore_mode: ALWAYS_OFF
    on_speed_set:
      then:
        - if:
            condition:
              lambda: |-
                return (id(ifan04).speed == 1 && id(ifan04).state);
            then:
              - switch.turn_on: relay1
              - switch.turn_off: relay2
              - switch.turn_off: relay3
        - if:
            condition:
              lambda: |-
                return (id(ifan04).speed == 2 && id(ifan04).state);
            then:
              - switch.turn_on: relay1 # switch.turn_off: relay1 (slower)
              - switch.turn_on: relay2
              - switch.turn_off: relay3
        - if:
            condition:
              lambda: |-
                return (id(ifan04).speed == 3 && id(ifan04).state);
            then:
                - switch.turn_off: relay1
                - switch.turn_off: relay2
                - switch.turn_on: relay3
    on_turn_off:
      then:
        - switch.turn_off: relay1
        - switch.turn_off: relay2
        - switch.turn_off: relay3

light:
  - platform: binary
    id: ifan04_light
    name: "Light"
    output: ifan04_light_output
    restore_mode: RESTORE_DEFAULT_OFF

switch:
  - platform: template
    id: buzzer
    name: "Buzzer"
    optimistic: True
  - platform: gpio
    id: relay1
    pin: 14
    restore_mode: ALWAYS_OFF
    interlock: [relay3]
  - platform: gpio
    id: relay2
    pin: 12
    restore_mode: ALWAYS_OFF
    interlock: [relay3]
  - platform: gpio
    id: relay3
    pin: 15
    restore_mode: ALWAYS_OFF
    interlock: [relay1, relay2]

output:
  - platform: template
    id: ifan04_output
    type: float
    write_action:
      - lambda: "return;"
  - platform: gpio
    id: ifan04_light_output
    pin: 9
    inverted: true
  - platform: gpio
    id: buzzer_output
    pin: 10
    inverted: true
